### ISSUE TITLE
Badge board type/name

### ISSUE THREAD

**Issue by bfpa40** [Algafix/pico-tesla-charging-port-opener#1]
What's the name of that small cicuitboard it's mounted on I can't seem to find it anywhere? I looked for a pimoroni badgelite but couldn't find it anywhere.,

**Comment by Algafix** [comment]
Hello!

It is called PIM528, but I think they discontinued it. You can find a bit of stock on other websites:

* https://www.digikey.be/en/products/detail/pimoroni-ltd/PIM528/13537129
* https://mou.sr/4eAMsWq
